remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: Ballet Activities!
description: |
  Puzzle your way to victory! While you are waiting for class or during the week!
github:
  is_project_page: false
show_downloads: false
