remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: RAD Ballet 🩰
description: |
  Take the opportunity to learn through puzzles and games!
github:
  is_project_page: false
show_downloads: false
